### ISSUE TITLE
External clock behavior

### ISSUE THREAD

**Issue by jjdeprisco** [knchaffin/Meander#10]
Great module!

Just trying to understand usage with an external clock. So far, I can not get Meander to follow an external clock, such as Impromptu's basic clock. Even with Run/Reset all properly configured, Meander seems to have a mind of its own, and in fact seems to slow down tremendously, even with BPM on the external set very high. The Meander display says 300, but it's not running at 300... just as an extreme example.
<img width="1083" alt="meander" src="https://user-images.githubusercontent.com/35905062/74109386-f6e6a900-4b50-11ea-8848-f9b91e2b76b4.png">

Can you recommend connections that make this work, or is this a bug?

**Comment by knchaffin** [comment]
If you are using an external clock, do not use the Meander BPM CV input.  The BPM CV control is only for the Meander internal clock without an external clock hooked up.  I used CLOCKED and set up a X8 clock and run it to the Meander EXT Clock input along with the RUN and RESET signals.  If Meander is set on 4/4 or any other N/4 time signature and both CLOCKED and Meander are set to the same BPM setting, the played tempo is the same regardless of whether the clock is coming from CLOCKED or is internal to Meander.  You should be able to drag the clock cable away from Meander EXT Clock input and the there should be no noticeable change in BPM or timing.

**Comment by knchaffin** [comment]
Meander is based on a 32nd note clock.  To determine the multiplier for the clock in CLOCKED, use 32/(Meander time_signature_bottom number) which is 32/4=8 in this case.  This info is in the Meander manual, but may be hard to find.

**Comment by jjdeprisco** [comment]
Cool, thanks!
