### ISSUE TITLE
seg fault when adjusting bass settings

### ISSUE THREAD

**Issue by ContemporaryInsanity** [knchaffin/Meander#13]
Can't reliably recreate but it's done it several times today.

[17269.228 fatal adapters/standalone.cpp:49 fatalSignalHandler] Fatal signal 11. Stack trace:
16: ./Rack() [0x403c8d]
15: /lib/x86_64-linux-gnu/libc.so.6(+0x46520)
14: /home/ewen/.Rack2/plugins/PS-PurrSoftware/plugin.so(MeanderWidget::step()+0x327)
13: ./libRack.so(rack::widget::Widget::step()+0x36)
12: ./libRack.so(rack::widget::Widget::step()+0x36)
11: ./libRack.so(rack::widget::Widget::step()+0x36)
10: ./libRack.so(rack::widget::Widget::step()+0x36)
9: ./libRack.so(rack::widget::Widget::step()+0x36)
8: ./libRack.so(rack::ui::ScrollWidget::step()+0x13)
7: ./libRack.so(rack::app::RackScrollWidget::step()+0x36f)
6: ./libRack.so(rack::widget::Widget::step()+0x36)
5: ./libRack.so(rack::window::Window::step()+0x593)
4: ./libRack.so(rack::window::Window::run()+0x28)
3: ./Rack(main+0xbe0)
2: /lib/x86_64-linux-gnu/libc.so.6(+0x2dfd0)
1: /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x7d)
0: ./Rack() [0x403bb9]

**Comment by knchaffin** [comment]
Is this happening when you change bass settings via knobs and buttons or via CV?  Which bass parameters have you been adjusting?  So far, I cannot reproduce in Windows.

**Comment by ContemporaryInsanity** [comment]
Knobs & buttons, haven't tried CV.

All of them!  As stated, cannot reliably reproduce but there does seem to be a problem somewhere.

**Comment by knchaffin** [comment]
I can imagine a scenario where the bass octaves mode is being toggled on an off and with the number of note channels changing from 1 to 2 and 2 to 1 that somewhere I am trying to write to an inactive channel array index.

**Comment by knchaffin** [comment]
This was determined to be related to a segfault if  a cable is connected to the Meander circle of 5ths STEP input.  This is corrected in V2.0.14
