### ISSUE TITLE
Module browser image

### ISSUE THREAD

**Issue by dbgrande** [knchaffin/Meander#14]
I noticed that the VCV Rack module browser adds ports, lights, and knobs, which don't quite line up with the ones on your png image, so I edited the image to remove them. I also tweaked the size by a couple of pixels and ran it through zopflipng to compress the png file.

![Meander-light](https://user-images.githubusercontent.com/64602967/161669612-9df08a28-f198-4a22-be4b-a152da7ed9af.png)

**Comment by knchaffin** [comment]
I will be working on this issue.

**Comment by dbgrande** [comment]
Your 2.0.16 update looks good.
