### ISSUE TITLE
Clarifications on EurostileBold.ttf usage

### ISSUE THREAD

**Issue by falkTX** [knchaffin/Meander#15]
Hi there.
Opening an issue asking for clarification of EurostileBold.ttf origins, is this from Windows?

I ask because I do not think using it as-is like you do is allowed.
Per https://docs.microsoft.com/en-us/typography/font-list/eurostile and (linked in that page) https://www.fonts.com/content/microsoft-typography one needs a license grant before being able to use such font.

I looked at the other fonts and they all seem fine. Only "Musisync" is a bit unclear / hard to find the origins, but you seem to no longer be using it (switched to Bravura). I will do a PR to remove it.

**Comment by falkTX** [comment]
https://fonts.google.com/specimen/Michroma seems to be a close and good replacement, with an open font license.

**Comment by knchaffin** [comment]
I have removed EurostileBold.ttf and Musicsync.ttf from repositry and code.

**Comment by falkTX** [comment]
Just using the Ubuntu font then, thanks!
