### ISSUE TITLE
LED Button suggestion

### ISSUE THREAD

**Issue by dbgrande** [knchaffin/Meander#17]
Just a suggestion, which you can either take or leave. Here's what Meander looks like using the MediumSimpleLight for your LED Buttons.

I had rolled my own flat lights at the beginning of 2.0, but I just discovered these have been in the 2.0 ComponentLibrary all along.

![MediumSimpleLight](https://user-images.githubusercontent.com/64602967/191599716-984ca66a-f2f6-466f-b868-50af6332e8ad.png)

**Comment by knchaffin** [comment]
This was changed in V2.0.23 .  LED buttons are now rendered with flat shading rather than 3D.
