### ISSUE TITLE
Adding this gem to Cardinal?

### ISSUE THREAD

**Issue by Vospi** [knchaffin/Meander#18]
Hey there! Wonderful project.
I'm not even through the manual yet, but I'm already really interested. In modular, that neat organized approach is I think really needed, and contained in one module, too. So! I am a big supporter of Cardinal, a self-contained fork of VCV 2. I'd really like to see that module there, and the current issue is: even to make them consider it the license has to be GPT 3+.

https://github.com/DISTRHO/Cardinal?tab=readme-ov-file#module-restrictions

I honestly don't even know the difference, and I'm for sure not here to tell people what to do, I just wanted to say that if that's a resolvable issue, then I'm sure an army of Cardinal users would love to have this multi-voice machine at their disposal. Didn't find another contact, so just went with the github.

**Comment by knchaffin** [comment]
Meander has been included in Cardinal for a couple of years.  Are you referring to Meander?  I have no control about what Cardinal ports and includes.  My VCV plugin is GPL V3.0.

**Comment by Vospi** [comment]
Oh, I see it now. Idk why I was so sure that it wasn't. I'm sorry!
Have a nice one!

пт, 2 февр. 2024 г. в 16:02, Ken Chaffin ***@***.***>:

**Comment by knchaffin** [comment]
No problem.
