### ISSUE TITLE
Latest update messing with module browser on linux

### ISSUE THREAD

**Issue by ContemporaryInsanity** [knchaffin/Meander#20]
![image](https://github.com/knchaffin/Meander/assets/12547379/ece95571-ef1b-45ff-8268-d02177d0b7f0)

**Comment by knchaffin** [comment]
This also happens occasionally in the current release.  Usually scrolling a bit will cause some type of refresh and the missing module images will show up.  I have not been able to understand this behavior, nor has any developer had any ideas.  I will keep trying to figure it out.  A few other plugins such as Voxglitch have exhibited this problem.

**Comment by knchaffin** [comment]
This problem has been resolved in V2.0.34 which has been submitted to the library for for review and build.

**Comment by knchaffin** [comment]
This bug is fixed in V2.0.34 of my plugin which is now available in the VCV library.
