### ISSUE TITLE
Staccato does not stay on

### ISSUE THREAD

**Issue by Petervos2018** [knchaffin/Meander#8]
Choose staccato in Harmony , close rack, open rack..... no staccato.
Melody and bass work the other way around, when you turn them off close rack open it they are on again.

Is this intentional/known should I have read this somewhere ?

Greetings Peter.

**Comment by knchaffin** [comment]
This is intentional.  To me, chords sound better as legato and melody and bass sound better as staccato.  I don't think I included this in the manual.

**Comment by Petervos2018** [comment]
So, some settings are not saved with the patch ? Is that really where you're going for ? Isn't it strange that you save a patch sounding one way and after reload it sounds different ? Maybe remove the option all together ? Maybe I'm making a big fuzz about nothing ;)
Love the module for what it does, so thank you for that,

Greetings Peter.

**Comment by knchaffin** [comment]
I will take a look at it.  It might be pretty simple to have the patch load not have settings go back to the default.  I'm probably forcing that and you are probably right that I should allow everything to be restored with the patch.

**Comment by gofaster** [comment]
In the Melody section, a saved patch also seems to default back to Chordal (if saved while Scaler was set).
Much gratitude for developing and releasing Meander.

**Comment by knchaffin** [comment]
Actually, all button parameter controls currently do not preserve their settings when saved and reloaded.  I'm not sure why and am trying to understand how to make buttons work like knobs.  I agree with you all that this needs to be fixed and I am working on it.  Thank you all for the suggestion.

**Comment by knchaffin** [comment]
The good news is that the button param states do get saved with the patch and reloaded.  The bad news is that  Meander is not handling that state properly when the patch is reloaded.  I'm still looking at it.

**Comment by knchaffin** [comment]
All button states now get saved, autosaved and reloaded as expected.  Now using json state variables mechanism.  There should be a new version released later in the week with these changes after I do more testing.

**Comment by knchaffin** [comment]
The V1.0,4 build request was just submitted, to VCV which implements these fixes.

**Comment by Petervos2018** [comment]
Thank you for 1.0.4, they seem to work, well done 👍
